version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    tty: true
    env_file:
      - .env.postgres.local
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./_backups:/home/postgres
      - ./_data:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - node-network

  client:
    image: mbaluev/next-auth-v5:latest
    platform: linux/x86_64
    container_name: client
    networks:
      - node-network
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - client
      - postgres

networks:
  node-network:
    driver: bridge