version: '3'

services:

  auth-postgres-service:
    container_name: auth-postgres
    image: postgres
    restart: always
    tty: true
    env_file:
      - ./.env.postgres.local
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./backups:/home/postgres
      - ./data:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - node-network

  auth-client-service:
    container_name: auth-client
    image: mbaluev/next-auth-v5:latest
    platform: linux/x86_64
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    env_file:
#      - ./client/.env.production.local
    networks:
      - node-network
    ports:
      - "3000:3000"

  auth-nginx-service:
    build:
      context: nginx
    container_name: auth-nginx-container
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - auth-client-service
      - auth-postgres-service

networks:
  node-network:
    driver: bridge
