name: build (mbaluev/next-auth-v5:latest)
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_URL: ${{ vars.APP_URL }}
          envkey_DATABASE_URL: ${{ vars.DATABASE_URL }}
          envkey_AUTH_SECRET: ${{ vars.AUTH_SECRET }}
          envkey_GIT_CLIENT_ID: ${{ vars.GIT_CLIENT_ID }}
          envkey_GIT_CLIENT_SECRET: ${{ vars.GIT_CLIENT_SECRET }}
          envkey_GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
          envkey_GOOGLE_CLIENT_SECRET: ${{ vars.GOOGLE_CLIENT_SECRET }}
          envkey_RESEND_API_KEY: ${{ vars.RESEND_API_KEY }}
          directory: client
          file_name: .env
#      - name: Create .env file
#        run: |
#          touch .env
#          echo APP_URL=${{ vars.APP_URL }} >> .env
#          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
#          echo AUTH_SECRET=${{ secrets.AUTH_SECRET }} >> .env
#          echo GIT_CLIENT_ID=${{ secrets.GIT_CLIENT_ID }} >> .env
#          echo GIT_CLIENT_SECRET=${{ secrets.GIT_CLIENT_SECRET }} >> .env
#          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
#          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
#          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
#          cat .env
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_NEXT_AUTH_V5 }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          dockerfile: ./client/Dockerfile
          tags: mbaluev/next-auth-v5:latest
