name: build (mbaluev/next-auth-v5:latest)
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: create client/.env file
        run: |
          cd client
          rm -f .env
          touch .env
          echo APP_NAME=${{ vars.APP_NAME }} >> .env
          echo APP_URL=${{ vars.APP_URL }} >> .env
          echo AUTH_URL=${{ vars.AUTH_URL }} >> .env
          echo AUTH_TRUST_HOST=${{ vars.AUTH_TRUST_HOST }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
          echo RESEND_DOMAIN=${{ vars.RESEND_DOMAIN }} >> .env
          echo AUTH_SECRET=${{ secrets.AUTH_SECRET }} >> .env
          echo AUTH_GITHUB_CLIENT_ID=${{ secrets.AUTH_GITHUB_CLIENT_ID }} >> .env
          echo AUTH_GITHUB_CLIENT_SECRET=${{ secrets.AUTH_GITHUB_CLIENT_SECRET }} >> .env
          echo AUTH_GOOGLE_CLIENT_ID=${{ secrets.AUTH_GOOGLE_CLIENT_ID }} >> .env
          echo AUTH_GOOGLE_CLIENT_SECRET=${{ secrets.AUTH_GOOGLE_CLIENT_SECRET }} >> .env
          echo POSTGRES_DB=${{ vars.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ vars.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          cat .env
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_NEXT_AUTH_V5 }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          dockerfile: ./client/Dockerfile
          tags: mbaluev/next-auth-v5:latest
